# This is a dictionary of the members of each ast node, a big Thanks to Thomas Kluyver from
# https://greentreesnakes.readthedocs.io/en/latest/
# for the ideas and most of the information.

# Python Library Dictionary PLD

PLD = {
    'Add': [],
    'alias': ['name', 'asname'],
    'And': [],
    'arg': ['arg', 'annotation'],
    'arguments': ['args', 'vararg', 'kwonlyargs', 'kwarg', 'defaults', 'kw_defaults'],
    'Assert': ['test', 'msg'],
    'Assign': ['targets', 'value'],
    'AsyncFor': ['target', 'iter', 'body', 'orelse'],
    'AsyncFunctionDef': ['name', 'args', 'body', 'decorator_list', 'returns'],
    'AsyncWith': ['items', 'body'],
    'Attribute': ['value', 'attr', 'ctx'],
    'AugAssign': ['target', 'op', 'value'],
    'Await': ['value'],
    'BinOp': ['left', 'op', 'right'],
    'BitAnd': [],
    'BitOr': [],
    'BitXor': [],
    'BoolOp': ['op', 'values'],
    'Break': [],
    'Bytes': ['s'],
    'Call': ['func', 'args', 'keywords'],
    'ClassDef': ['name', 'bases', 'keywords', 'body', 'decorator_list'],
    'Compare': ['left', 'ops', 'comparators'],
    'comprehension': ['target', 'iter', 'ifs'],
    'Continue': [],
    'Del': [],
    'Delete': ['targets'],
    'Dict': ['keys', 'values'],
    'DictComp': ['key', 'value', 'generators'],
    'Div': [],
    'Ellipsis': [],
    'Eq': [],
    'ExceptHandler': ['type', 'name', 'body'],
    'Expr': ['value'],
    'Expression': ['body'],
    'ExtSlice': ['dims'],
    'FloorDiv': [],
    'For': ['target', 'iter', 'body', 'orelse'],
    'FunctionDef': ['name', 'args', 'body', 'decorator_list', 'returns'],
    'GeneratorExp': ['elt', 'generators'],
    'Global': ['names'],
    'Gt': [],
    'GtE': [],
    'If': ['test', 'body', 'orelse'],
    'IfExp': ['test', 'body', 'orelse'],  # all are Name nodes
    'Import': ['names'],
    'ImportFrom': ['module', 'names', 'level'],
    'In': [],
    'Index': ['value'],
    'Invert': [],  # the '~' operator
    'Is': [],
    'IsNot': [],
    'keyword': ['arg', 'value'],
    'Lambda': ['args', 'body'],
    'List': ['elts', 'ctx'],
    'ListComp': ['elt', 'generators'],
    'Load': [],
    'LShift': [],
    'Lt': [],
    'LtE': [],
    'MatMult': [],  # new in 3.5 matrix multiplier '@'
    'Mod': [],
    'Module': ['body'],
    'Mult': [],
    'Name': ['id', 'ctx'],
    'NameConstant': ['value'],
    'Nonlocal': ['names'],
    'Not': [],   # the 'not' keyword
    'NotEq': [],
    'NotIn': [],
    'Num': ['n'],
    'Or': [],
    'Pass': [],
    'Pow': [],
    'Raise': ['exc', 'cause'],
    'Return': ['value'],
    'RShift': [],
    'Set': ['elts'],
    'SetComp': ['elt', 'generators'],
    'Slice': ['lower', 'upper', 'step'],
    'Starred': ['value', 'ctx'],
    'Store': [],
    'Str': ['s'],
    'Sub': [],
    'Subscript': ['value', 'slice', 'ctx'],
    'Suite': ['body'],
    'Try': ['body', 'handlers', 'orelse', 'finalbody'],
    'Tuple': ['elts', 'ctx'],
    'UAdd': [],
    'UnaryOp': ['op', 'operand'],
    'USub': [],
    'While': ['test', 'body', 'orelse'],
    'With': ['items', 'body'],
    'withitem': ['context_expr', 'optional_vars'],
    'Yield': ['value'],
    'YieldFrom': ['value'],
}

# a list of some ast nodes that are lists
PLDLIST = ['body',                'args',                'arguments',
           'kw_defaults',         'kwonlyargs',          'defaults',
           'targets',             'values',              'ops',
           'comparators',         'orelse',              'decorator_list',
           ]
